import { Medicine } from '@/types';

export const medicines: Medicine[] = [
  {
    id: 'med-paracetamol',
    name: 'Paracetamol 650mg',
    category: 'Pain Relief',
    description: 'Rapid-acting pain reliever and fever reducer. Essential for headaches, muscle soreness, and travel fevers.',
    activeIngredient: 'Paracetamol 650mg',
    dosage: '1 tablet every 4-6 hours as needed. Do not exceed 4 tablets in 24 hours.',
    warning: 'Do not consume alcohol. Severe liver damage may occur if daily limit is exceeded.',
    sideEffects: 'Generally safe. Rare allergic reactions or rashes.',
    fdaStatus: 'CDSCO Regulated / WHO Essential',
    travelNote: 'Globally recognized and legal in all countries.',
    compartment: 'A',
    alternative: 'Crocin, Dolo 650, Calpol',
    symptoms: ['Headache', 'Fever', 'Body Aches', 'Toothache']
  },
  {
    id: 'med-ibuprofen',
    name: 'Ibuprofen 400mg',
    category: 'Pain Relief',
    description: 'Anti-inflammatory medicine that targets swelling, joint stiffness, toothache, and deep muscular pain.',
    activeIngredient: 'Ibuprofen 400mg',
    dosage: '1 tablet every 6-8 hours with food. Do not exceed 3 tablets in 24 hours.',
    warning: 'May cause stomach irritation. Avoid if you have active ulcers.',
    sideEffects: 'Nausea, heartburn, mild stomach discomfort.',
    fdaStatus: 'CDSCO Regulated / OTC',
    travelNote: 'Must be taken with food. Ideal for recovery after long walks or mountain climbs.',
    compartment: 'A',
    alternative: 'Brufen, Advil',
    symptoms: ['Joint Pain', 'Toothache', 'Muscle Sprain', 'Swelling']
  },
  {
    id: 'med-diclofenac',
    name: 'Diclofenac 50mg',
    category: 'Pain Relief',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) designed to target acute backaches, neck stiffness, and joint soreness.',
    activeIngredient: 'Diclofenac Sodium 50mg',
    dosage: '1 tablet twice daily after meals.',
    warning: 'Do not take on an empty stomach. Avoid taking with other oral NSAIDs.',
    sideEffects: 'Mild dizziness, stomach discomfort, acid reflux.',
    fdaStatus: 'CDSCO Regulated / Prescription',
    travelNote: 'Excellent rapid action for sudden cramps or heavy backpack fatigue.',
    compartment: 'A',
    alternative: 'Voveran, Voltaren',
    symptoms: ['Backache', 'Neck Pain', 'Arthritic Flares', 'Severe Muscle Pain']
  },
  {
    id: 'med-aceclofenac',
    name: 'Aceclofenac 100mg',
    category: 'Pain Relief',
    description: 'Effective anti-inflammatory medication targeting bone and joint discomfort, dental extraction recovery, and sprains.',
    activeIngredient: 'Aceclofenac 100mg',
    dosage: '1 tablet in the morning and 1 at night after food.',
    warning: 'Ensure adequate hydration during use to protect kidney function.',
    sideEffects: 'Indigestion, mild drowsiness, headache.',
    fdaStatus: 'CDSCO Regulated / Prescription',
    travelNote: 'Highly stable in tropical climates. Best kept in foil packaging.',
    compartment: 'A',
    alternative: 'Zerodol, Hifenac',
    symptoms: ['Dental Pain', 'Sprains', 'Osteoarthritis discomfort', 'Severe body ache']
  },
  {
    id: 'med-combiflam',
    name: 'Combiflam Tablet',
    category: 'Pain Relief',
    description: 'A powerful combination of Paracetamol and Ibuprofen to provide dual action against severe pain and fever.',
    activeIngredient: 'Ibuprofen 400mg + Paracetamol 325mg',
    dosage: '1 tablet up to 3 times a day after meals.',
    warning: 'Do not use if allergic to aspirin or other NSAIDs.',
    sideEffects: 'Heartburn, nausea, minor rash.',
    fdaStatus: 'CDSCO Regulated / Popular Generic Brand',
    travelNote: 'A trusted go-to medicine across India for immediate multi-pain relief.',
    compartment: 'A',
    alternative: 'Flexon, Ibugesic Plus',
    symptoms: ['High Fever', 'Migraine', 'Joint Pain', 'Severe Toothache']
  },
  {
    id: 'med-loperamide',
    name: 'Loperamide 2mg',
    category: 'Digestion',
    description: 'Fast-acting anti-diarrheal compound. Slows bowel movements to control diarrhea and restore digestive balance.',
    activeIngredient: 'Loperamide HCl 2mg',
    dosage: '2 tablets immediately after the first loose stool, then 1 tablet after each loose stool. Max 4 tablets daily.',
    warning: 'Do not use in case of dysentery (blood in stool) or high fever.',
    sideEffects: 'Constipation, dry mouth, mild abdominal cramps.',
    fdaStatus: 'CDSCO Regulated / OTC',
    travelNote: 'Essential for travellers visiting destinations with risk of food/water contamination.',
    compartment: 'B',
    alternative: 'Lopamide, Imodium',
    symptoms: ['Diarrhea', 'Loose Stools', 'Traveller\'s Tummy']
  },
  {
    id: 'med-digene',
    name: 'Digene Antacid Tablet',
    category: 'Digestion',
    description: 'Chewable antacid tablet providing quick relief from acidity, gas, bloating, and burning sensation in stomach.',
    activeIngredient: 'Magnesium Hydroxide, Aluminium Hydroxide, Simethicone',
    dosage: 'Chew 2-4 tablets after meals or when experiencing symptoms.',
    warning: 'Do not swallow whole; chew thoroughly for immediate effect.',
    sideEffects: 'None under recommended usage. High doses may affect bowel consistency.',
    fdaStatus: 'CDSCO Regulated / OTC',
    travelNote: 'Perfect companion when sampling local street food and rich culinary dishes.',
    compartment: 'B',
    alternative: 'Gelusil, Tums',
    symptoms: ['Acidity', 'Heartburn', 'Bloating', 'Indigestion']
  },
  {
    id: 'med-avomine',
    name: 'Avomine 25mg',
    category: 'Digestion',
    description: 'Effective medication for prevention and treatment of motion sickness, nausea, and travel-induced vomiting.',
    activeIngredient: 'Promethazine Theoclate 25mg',
    dosage: 'Take 1 tablet 1-2 hours before travel. Repeat after 6-8 hours if journey is long.',
    warning: 'Causes marked drowsiness. Avoid driving or alcohol intake.',
    sideEffects: 'Drowsiness, dry mouth, blurred vision.',
    fdaStatus: 'CDSCO Regulated / Travel Category Standard',
    travelNote: 'Invaluable for winding mountain roads, ferry trips, or long bumpy bus rides.',
    compartment: 'B',
    alternative: 'Phenergan, Gravol',
    symptoms: ['Motion Sickness', 'Nausea', 'Vomiting', 'Car Sickness']
  },
  {
    id: 'med-ors',
    name: 'ORS Hydration Salts',
    category: 'Digestion',
    description: 'WHO-formula Oral Rehydration Salts designed to restore body fluids and key electrolytes lost during illness or extreme heat.',
    activeIngredient: 'Sodium Chloride, Potassium Chloride, Sodium Citrate, Dextrose',
    dosage: 'Dissolve entire contents of 1 sachet in 1 litre of clean drinking water. Consume within 24 hours.',
    warning: 'Do not mix with milk or juice. Use only safe drinking water.',
    sideEffects: 'None.',
    fdaStatus: 'WHO Standard Hydration Formula',
    travelNote: 'Critical for tropical climates, desert exploration, or recovering from stomach bugs.',
    compartment: 'B',
    alternative: 'Electral, ORS Powder',
    symptoms: ['Dehydration', 'Heat Stroke', 'Dizziness', 'Fatigue']
  },
  {
    id: 'med-cetirizine',
    name: 'Cetirizine 10mg',
    category: 'Allergies',
    description: 'Second-generation non-drowsy antihistamine providing 24-hour relief from allergies, runny nose, and sneezing.',
    activeIngredient: 'Cetirizine HCl 10mg',
    dosage: '1 tablet daily at bedtime.',
    warning: 'May cause mild drowsiness in sensitive individuals. Do not exceed 1 tablet daily.',
    sideEffects: 'Dry mouth, mild fatigue, headache.',
    fdaStatus: 'CDSCO Regulated / 24h Antihistamine',
    travelNote: 'Excellent for destinations with high pollen counts or different seasonal allergens.',
    compartment: 'C',
    alternative: 'Alerid, Zyrtec',
    symptoms: ['Sneezing', 'Allergic Rhinitis', 'Hives', 'Watery Eyes']
  },
  {
    id: 'med-diphenhydramine',
    name: 'Emergency Antihistamine',
    category: 'Allergies',
    description: 'Rapid-acting antihistamine used for severe allergic reactions, insect bites, and itching.',
    activeIngredient: 'Diphenhydramine HCl 25mg',
    dosage: '1-2 tablets every 4-6 hours. Max 6 tablets in 24 hours.',
    warning: 'Causes heavy drowsiness. Do not drive or operate machinery.',
    sideEffects: 'Sleepiness, dry throat, coordination impairment.',
    fdaStatus: 'CDSCO Regulated / Emergency Med',
    travelNote: 'Also highly effective as a short-term sleep aid for adjusting to time-zone shifts.',
    compartment: 'C',
    alternative: 'Benadryl',
    symptoms: ['Insect Bites', 'Severe Itching', 'Acute Hives', 'Allergic Flare']
  },
  {
    id: 'med-decongestant',
    name: 'Cough & Cold Decongestant',
    category: 'Respiratory',
    description: 'Provides relief from nasal congestion, sinus pressure, runny nose, and throat irritation associated with common cold.',
    activeIngredient: 'Phenylephrine HCl + Chlorpheniramine Maleate',
    dosage: '1 tablet every 6 hours. Max 4 tablets daily.',
    warning: 'May cause mild restlessness. Monitor blood pressure if hypertensive.',
    sideEffects: 'Dryness of throat, mild dizziness, dry nose.',
    fdaStatus: 'CDSCO Regulated / OTC Cold Combo',
    travelNote: 'Keeps sinus passages open during high-altitude flights to prevent ear blocks.',
    compartment: 'C',
    alternative: 'Solvin Cold, Sinarest',
    symptoms: ['Runny Nose', 'Sinus Pressure', 'Nasal Blockage', 'Cold & Cough']
  },
  {
    id: 'med-amoxicillin',
    name: 'Amoxicillin 500mg',
    category: 'Anti-Infectives',
    description: 'Broad-spectrum antibiotic used to treat bacterial infections of the chest, throat, urinary tract, and skin.',
    activeIngredient: 'Amoxicillin Trihydrate 500mg',
    dosage: '1 tablet three times daily for 5-7 days. Always finish the prescribed course.',
    warning: 'Do not use if allergic to Penicillin. Requires teleconsultation confirmation.',
    sideEffects: 'Stomach upset, mild diarrhea, nausea.',
    fdaStatus: 'CDSCO Regulated / Prescription Only',
    travelNote: 'Included for emergencies. Use only after scanning kit QR and speaking with a doctor.',
    compartment: 'C',
    alternative: 'Novamox, Amoxil',
    symptoms: ['Throat Infection', 'Chest Infection', 'Bacterial Scratches', 'UTI Symptoms']
  },
  {
    id: 'med-bandaid',
    name: 'Band-Aid & Wound Dressings',
    category: 'Wound Care',
    description: 'Premium adhesive strips and sterile dressing pads. Protects minor cuts, scrapes, and blisters from dust and infection.',
    activeIngredient: 'Sterile Adhesive Dressings',
    dosage: 'Apply to cleaned and disinfected skin. Change daily.',
    warning: 'Ensure wound is clean before sealing.',
    sideEffects: 'None. Minimal adhesive irritation in rare skin types.',
    fdaStatus: 'Clinical First Aid Standard',
    travelNote: 'Pack includes various sizes, including flexible fabric strips ideal for joints and blisters.',
    compartment: 'First Aid Pouch',
    alternative: 'Plasters, Bandages',
    symptoms: ['Cuts', 'Scrapes', 'Blisters', 'Minor Bleeding']
  },
  {
    id: 'med-antibiotic-ointment',
    name: 'Triple Antibiotic Ointment',
    category: 'Wound Care',
    description: 'Topical antibiotic ointment that prevents local infection in minor cuts, scrapes, and burns.',
    activeIngredient: 'Bacitracin + Neomycin + Polymyxin B',
    dosage: 'Clean the area. Apply a thin layer 1-3 times daily.',
    warning: 'For external skin use only. Do not apply in eyes or large open wounds.',
    sideEffects: 'None. Rare local skin redness.',
    fdaStatus: 'CDSCO Regulated / USP Grade',
    travelNote: 'Apply after sanitizing the wound and before cover with a Band-Aid.',
    compartment: 'First Aid Pouch',
    alternative: 'Neosporin',
    symptoms: ['Minor Scrapes', 'Light Burns', 'Cuts', 'Skin Abrasions']
  },
  {
    id: 'med-thermometer',
    name: 'Digital Thermometer',
    category: 'First Aid',
    description: 'High-accuracy oral or underarm digital thermometer. Essential for tracking body temperature spikes.',
    activeIngredient: 'N/A (Electronic Device)',
    dosage: 'Place under tongue or armpit. Wait for beep. Read digital screen.',
    warning: 'Do not submerge under boiling water. Clean with antiseptic wipes after use.',
    sideEffects: 'None.',
    fdaStatus: 'ISO Certified Medical Device',
    travelNote: 'Uses standard button battery. Compact and shock-proof casing.',
    compartment: 'First Aid Pouch',
    alternative: 'Electronic Temp Sensor',
    symptoms: ['High Fever', 'Chills', 'Temperature Tracking']
  }
];
